exclude: ^(.*\/migrations\/.*|diagrams\/.*)$
default_language_version:
    python: python3.10
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-ast
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-yaml
    - id: debug-statements
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: mixed-line-ending
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
    - id: pyupgrade
      args: ["--py38-plus"]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort
-   repo: https://github.com/PyCQA/autoflake
    rev: v1.5.3
    hooks:
    - id: autoflake
