version: '3.8'

name: sentiment-analysis

services:
  scrapy_splash:
    image: scrapinghub/splash
    restart: always
    ports:
      - '8050:8050'

  crawler:
    build:
      context: ./
      dockerfile: app/crawler/Dockerfile
    env_file:
      - .env
    depends_on:
      - scrapy_splash
      - db

  cache:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-stack-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/var/lib/redis-stack

  db:
    image: postgres:15.2-alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db_sentiment:/var/lib/postgresql/data

  sentiment:
    build:
      context: ./
      dockerfile: app/sentiment/Dockerfile
    env_file:
      - .env
    restart: always
    depends_on:
      - cache

  schedule_extraction_beat:
    build:
      context: ./
      dockerfile: app/sentiment/Dockerfile.beat
    env_file:
      - .env
    restart: always

  webapi:
    build:
      context: ./
      dockerfile: app/webapi/Dockerfile
    env_file:
      - .env
    ports:
      - 80:80
    command: /app/prestart.sh
    # command: tail -f /dev/null
    restart: always
    depends_on:
      - db

volumes:
  cache:
    driver: local
  db_sentiment:
    driver: local
