version: '3.8'

name: sentiment-analysis

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: postgres:15.2-alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db_sentiment:/var/lib/postgresql/data

  sentiment:
    build:
      context: ./
      dockerfile: app/sentiment/Dockerfile
    env_file:
      - .env
    restart: always
    depends_on:
      - rabbitmq

  webapi:
    build:
      context: ./
      dockerfile: app/webapi/Dockerfile
    env_file:
      - .env
    command: /app/prestart.sh
    # command: tail -f /dev/null
    restart: always
    depends_on:
      - db

volumes:
  mongodb_data:
    driver: local
  db_sentiment:
    driver: local
