"""first

Revision ID: 95a907ad10b7
Revises:
Create Date: 2023-07-09 22:37:04.454938

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "95a907ad10b7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "restaurant",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.Column("address", sa.VARCHAR(), nullable=True),
        sa.Column("url", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_restaurant_name"), "restaurant", ["name"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("username", sa.VARCHAR(), nullable=False),
        sa.Column("password", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "comment",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("content", sa.TEXT(), nullable=True),
        sa.Column("rating", sa.FLOAT(), nullable=True),
        sa.Column("model_prediction", sa.VARCHAR(), nullable=True),
        sa.Column("need_review", sa.BOOLEAN(), nullable=True),
        sa.Column("verified_result", sa.VARCHAR(), nullable=True),
        sa.Column("report_comment", sa.TEXT(), nullable=True),
        sa.Column("url", sa.VARCHAR(), nullable=True),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.Column("restaurant_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurant.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comment")
    op.drop_table("user")
    op.drop_index(op.f("ix_restaurant_name"), table_name="restaurant")
    op.drop_table("restaurant")
    # ### end Alembic commands ###
